### ISSUE TITLE
Change Tika version on install

### ISSUE THREAD

**Issue by jciccolini** [critocrito/sugarcube#28]
@sugarcube/utils/install.js file is set to download an old version of Tika (1.22) from a broken link and fails. Should change to latest Tika version.

**Comment by critocrito** [comment]
@jciccolini Thanks for letting me know.

I bumped the version to 1.23 for now. I might bundle Tika with the npm package in the future to avoid the same issue in the future. I just published 0.35.0 on npm that contains the fix.
